### ISSUE TITLE
Настройка

### ISSUE THREAD

**Issue by dm02111978** [AntukhSerg/AVR_ModBus#4]
Здравствуйте, могли бы помочь разобраться с настройкой - не могу запустить ваш код на устройстве.

**Comment by AntukhSerg** [comment]
Добрый день!
Напишите, что именно не получается. Постараюсь вспомнить как это работает.

**Comment by dm02111978** [comment]
Здравствуйте,

Попробую сейчас с аппаратной разобраться - может у меня переходник rs-485 -
ttl  не работает... У меня задача сделать обмен между моими двумя
устройствами- блок управления и панель индикации/управления. Блок это
мастер, панель клиент. Пока я тестирую схему на монтажке, установлена
atmega8. Мастером является  modbus poll, слэйв соответственно моя атмега.
При соединении timeout... Я сам пока в процессе обучения МК avr и языка си,
поэтому некоторые вещи мне не совсем понятны. С протоколом Modbus
сталкивался только на готовых устройствах промышленных. Если поможете мне
сделать проект, на базе вашей библиотеки готов оплатить вашу работу.

С уважением,
Дмитрий Михайлов

вторник, 9 апреля 2024 г. пользователь AntukhSerg ***@***.***>
написал:

**Comment by dm02111978** [comment]
И еще подскажите у вас вот такая настройка USART
#define UCSRB_SET() UCSRB=(1<<RXEN)|(1<<TXEN)|(1<<RXCIE)|(0<<TXCIE)
#define UCSRC_SET() UCSRC=(1<<URSEL)|(1<<UCSZ0)|(1<<UCSZ1) //8bit, Even,
1stop.bit

Но разве Even это не установка бита  вот так? |(1<<UPM1)

вт, 9 апр. 2024 г. в 16:52, Jera Studio ***@***.***>:

**Comment by AntukhSerg** [comment]
Заниматься проектом не смогу, своих достаточно.

_Но разве Even это не установка бита  вот так? |(1<<UPM1)_
Все верно, комментарий остался от предыдущей настройки.
Хорошее пояснение по протоколу modbus тут:
https://ipc2u.ru/articles/prostye-resheniya/modbus-rtu/

Проверьте через терминал есть ли вообще связь с МК (без модуля modbus)

Проверьте настройки (в .h) :
соответствует ли частоте МК - #define F_CPU 8000000L 

соотвествует ли скорости соединения - #define BAUD_RATE 9600L

по тому ID обращаетесь или нет - #define SLAVE_ID 0x0A

для избежания проблем лучше заменить в .h это:
//запуск таймера0 для контроля паузы 3,5символа
#define StartTimer0() TCCR0=1<<CS02;  TCNT0=130; 
на это:
//запуск таймера0 для контроля паузы 3,5символа
#define StartTimer0() TCCR0|=1<<CS02;  TCNT0=130; 

закомментируйте проверку CRC в файле .c:
 if (CRC16) return 0;  //контрольная сумма не совпадает, ответ не нужен

можно слать запросы напрямую из терминала

$0A$01$00$00$00$01$FC$B1

$0A$02$00$01$00$02$A9$70

$0A$03$04$B0$00$02$C5$A7

$0A$04$03$E8$00$04$70$C2

$0A$05$00$01$FF$00$DC$81

$0A$06$00$01$00$07$98$B3

$0A$05$00$05$FF$00$9D$40

$0A$05$00$05$00$00$DC$B0

$0A$01$00$05$00$01$EC$B0

не помню все ли они корректные (могут быть и не корректными для проверки)
но хотя бы на один должен ответить.

**Comment by AntukhSerg** [comment]
Какой вариант используется, обычный или с глобальным временем (GT)?

**Comment by dm02111978** [comment]
я использую вариант кода с глобальным временем:

//запуск таймера глобального вермени с периодом 0.1мс для 8МГц
#define GLOBAL_TIME_START() TCCR0 |= (1<<CS01);\
TIMSK |= (1<<TOIE0);\
TCNT0 = 156

Запустить код удалось - повесил кварц 8мГц на МК, без него не хочет.
Регистры пишет\читает.

Буду читать\разбираться, так как не все и не совсем понятно пока. Я так
понимаю этот код -работа как slave. А мне все равно нужно еще понять как
master запускать т.к. у меня master тоже будет МК.

Можно будет к вам обратиться, если совсем будет непонятно?

С уважением,
      Дмитрий Михайлов

вт, 9 апр. 2024 г. в 23:10, AntukhSerg ***@***.***>:

**Comment by AntukhSerg** [comment]
Да, без кварца UART работать нормально не будет. 
Код работает как Slave.
Можно, если смогу, подскажу.
